---
version: 0.2

env:
  parameter-store:
    AWS_ACCESS_KEY: "/golden-image-linux/example/aws_access_key_id"
    AWS_SECRET_KEY: "/golden-image-linux/example/aws_secret_access_key"
    
phases:
  pre_build:
    commands:
      - echo "Setting up Git authentication using PAT..."
      - yum update -y
      - echo "Using Python 3..."
      - python3 --version
      - SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-west-2:716514200744:secret:pat_gh-b7FRfI --query SecretString --output json)
      - GITHUB_PAT=$(echo $SECRET_VALUE | python -c "import sys, json; print(json.loads(json.load(sys.stdin))['PAT'])")
      - echo "Setting environment variable for Git authentication..."
      - export GIT_ASKPASS=$(pwd)/git-askpass.sh
      - echo -e '#!/bin/sh\necho $GITHUB_PAT' > $GIT_ASKPASS
      - chmod +x $GIT_ASKPASS
      - echo "Cloning the repository using PAT..."
      - git clone https://github.com/ManjunathanRajan/golden-image-linux.git
      - echo "Changing the working directory to the cloned repository..."
      - cd golden-image-linux
      - echo "Setting Git user name and email for this repository..."
      - git config user.email "manjun566@gmail.com"
      - git config user.name "ManjunathanRajan"
      - echo "Pulling the latest changes from the main branch..."
      - git checkout main
      - git pull origin main
      - echo "Fetching the latest tag and incrementing the tag number..."
      - LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "GA-00")
      - NEW_TAG_NUMBER=$((10#${LATEST_TAG:3} + 1))
      - NEW_TAG="GA-$(printf "%02d" $NEW_TAG_NUMBER)"
      - TAG_MESSAGE="Release $NEW_TAG"
      - echo "Creating a new tag..."
      - git tag $NEW_TAG -m "$TAG_MESSAGE"
      - echo "Pushing the new tag to the original GitHub repository..."
      - git push origin $NEW_TAG
      - echo "Making create_github_release.sh script executable..."
      - chmod +x create_github_release.sh
      - echo "Creating a release on GitHub..."
      - ./create_github_release.sh "$NEW_TAG" "$GITHUB_PAT"

  build:
    commands:
      - chmod a+x *.sh
      - ./main.sh

artifacts:
  files:
    - '**/*'
